name: lint
"on": pull_request
jobs:
  goodcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Analyze code statically using Goodcheck
        uses: moneyforward/goodcheck-action@v0
